name: flutter_tech_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: 0.13.4
  cupertino_icons: ^1.0.2
  
  # State management and dependency injection
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3
  
  # Localization
  intl: ^0.19.0
  
  # Utilities
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
  # Code generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  
  # Testing
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  
  # Localization
  generate: true